### ISSUE TITLE
Manager코드 싱글톤InfraStructure코드 재활용

### ISSUE THREAD

**Issue by gdevhun** [gdevhun/OSSTeamProject#15]
메니저들 작성할때! 
개별 인스턴스 생성해서 싱글톤으로 개별 스크립트에서 생성시키지말고, 유지보수, 코드 생산성을 위해서
[https://github.com/gdevhun/OSSTeamProject/blob/main/Assets/03.Scripts/Singleton/Singleton.cs](url)
**싱글톤 기반코드 상속**받아서 편리하게 관리합시다!

**Comment by Hyodonjoo** [comment]
확인했습니다

**Comment by CoEf** [comment]
알겠습니다

**Comment by gdevhun** [comment]
광철님 Refactor commit 확인했습니다. Issue close 하겠습니다!
