### ISSUE TITLE
AggregateException 평탄화로 예외 상세 처리

### ISSUE THREAD

**Issue by KRavie403** [gdevhun/OSSTeamProject#21]
오류 처리 할 때 task.Exception 객체가 null이 아닐 때 적절히 로깅하고 있지만, AggregateException을 확인하고 내부의 실제 예외를 추출해야 할 수도 있습니다! 

이 예외들을 평탄화(flatten)하여 각각을 독립적으로 접근하고 분석함으로써 더 정확한 오류 메시지를 얻을 수 있습니다.
이를 통해 비동기 작업에서 여러 예외가 발생할 때 각각을 따로 처리할 수 있게 해줍니다. 

### 추가 설명
**<task.Exception>**
```csharp
        if (task.Exception != null) {
                Debug.Log(task.Exception.ToString());
        }
```
> 'AggregateException'에 포함된 모든 오류 정보가 한 번에 출력됩니다. 이는 오류 메시지가 길고 복잡해져 실제 문제의 원인을 파악하기 어려울 수 있습니다.

**<AggregateException 평탄화>**
```csharp
        using System;
        
        if (task.IsFaulted) {
            // AggregateException을 평탄화하여 각각의 예외를 처리
            foreach (Exception ex in task.Exception.Flatten().InnerExceptions) {
                Debug.Log($"Exception caught: {ex.Message}");
            }
       }
```
> 'task.Exception.Flatten().InnerExceptions를 반복 처리하면서 각 예외의 메시지를 별도로 로깅합니다. 이 경우, 첫 번째 로그에서 "데이터베이스 연결 실패"라는 메시지가, 두 번째 로그에서는 "요청된 데이터가 없음"이라는 메시지가 출력됩니다. 각 문제에 대해 명확한 메시지를 제공함으로써 정확한 오류 원인을 빠르게 파악할 수 있습니다!

**Comment by Hyodonjoo** [comment]
좀 더 효율적으로 작업할 수 있다고 생각합니다. 해당 예외처리 방식을 적극 활용해야겠다고 생각드네요. 개선사항 감사합니다
