### ISSUE TITLE
HTTP 통신에서 Coroutine을 대체할 비동기 OSS UniTask

### ISSUE THREAD

**Issue by gdevhun** [gdevhun/OSSTeamProject#22]
흔히 UnitySDK는 Coroutine을 활용하여 HTTP 통신을 합니다.
하지만 유니티의 Coroutine은 매우 비효율적인 성능을 가지고 있다고 알려져 있습니다. 
시간을 대기하는 작업에서 지속적인 GC가 생기는 큰 단점을 가지고 있습니다.
또한 저희 수업이 OSS 이기 때문에 OSS를 활용해서 프로젝트 개발에 도입한다면 수업의 방향성과도 가깝다고 생각합니다.

Why UniTask ?
💡Coroutine의 단점
유니티에서 비동기작업(Async Task)을 할 때 흔히 Coroutine, Invoke 등을 이용한다. 하지만 이는 효율적이지 않아 필요할 때만 사용하고 왠만하면 피하도록 권장한다. 특히 유니티 코루틴은 HTTPS 통신에서 서버로부터 받은 값을 리턴할 수 없으며 StartCoroutine()을 사용할 때 마다 GC할당이 높고, yield return new~()를 사용할 때 new에 대한 할당이 지속적으로 발생한다.

💡UniTask의 장점 
Struct 기반이라 Zero Allocation이 특징이다.
서버로부터 받은 값을 리턴할 수 있다.
UniTask.Yield, Delay, DelayFrame 처럼 코루틴의 유사한 기능을 제공한다.
메모리 누수 방지를 확인할 수 있는 GUI TaskTracker 창을 제공한다.

다음은 같이 저희 FirebaseAuthManager에 작성된 코루틴을 활용한 함수입니다.
```
private IEnumerator CheckAndFixDependenciesAsync()
    {
        var dependencyTask = FirebaseApp.CheckAndFixDependenciesAsync();
        yield return new WaitUntil(() => dependencyTask.IsCompleted);

        dependencyStatus = dependencyTask.Result;

        if (dependencyStatus == DependencyStatus.Available)
        {
            InitializeFirebase();
        }
        else
        {
            Debug.LogError("Could not resolve all firebase dependencies: " + dependencyStatus);
        }
    }
```
```
 private async UniTask CheckAndFixDependenciesAsync()
    {
        var dependencyTask = FirebaseApp.CheckAndFixDependenciesAsync();
        await dependencyTask;

        dependencyStatus = dependencyTask.Result;

        if (dependencyStatus == DependencyStatus.Available)
        {
            InitializeFirebase();
        }
        else
        {
            Debug.LogError("Could not resolve all Firebase dependencies: " + dependencyStatus);
        }
    }
```
와 같이 대체할 수 있습니다.

관련 유튜브영상을 시청하면 코드 리팩토링에 더 도움이 될 것이라고 생각합니다.
https://youtu.be/j3hpuVB2cLk?si=zHgG2I2sotxgOylt

**Comment by KRavie403** [comment]
제안하신 UniTask를 사용하는 방안에 대해 긍정적으로 생각합니다!
Firebase Realtime DB의 경우, 'Task' 기반으로 동작하고 UniTask는 이러한 'Task'를 'UniTask'로 변환하는 기능을 제공하고 있어 구현 방식이 Coroutine 보다 효율적으로 보입니다.
