### ISSUE TITLE
백엔드 서버 구축

### ISSUE THREAD

**Issue by Hyodonjoo** [gdevhun/OSSTeamProject#29]
현재 저희 프로젝트는 모든 작업이 Unity 내에서 수행되고 있습니다.
6/3 교수님과 진행상황 면담을 통해, 현재 이렇게 한 Unity 내에서 모든 작업이 이루어질 경우, 통신 관련 부분에서 점수가 없을 거라고 하셨습니다. 

이러한 면담을 기반으로 백엔드 서버를 구축해서, 현재 Unity에 있던 스크립트들을 서버로 옮기고, unity에서 만든 프로그램은 서버에 토큰을 보내서 통신하여 스크립트를 불러오거나, 결과를 호출하는 방식으로 해야할것 같습니다. 

백엔드 하시는 저희가 모두 백엔드 서버를 구축하는 것을 1순위로 둬야 할 것 같습니다.

현재 찾아본 결과로는 다음과 같은 서버 구축방식이 있는데, 이에 대한 의견 부탁드립니다.
***
## C# 파일 그대로 옮기기만 해서 동작하도록 서버 구축

1. Photon Server 
https://doc.photonengine.com/ko-kr/server/v4/getting-started/photon-server-intro
![1](https://github.com/gdevhun/SpaceCat/assets/102202498/f8b24848-723c-474f-a534-ea4e367d39ef)
멀티플레이 게임 전용 서버
Unity 전용 서버로 호환성이 좋음 
2. Winodw Serever 
GUI 형태로 가장 개발하기 편함. 관련된 정보가 가장 많음.
단, 서버로 개인 PC로 할 건지, 클라우드로 할건지 정해야함.
프로젝트 평가시, TA가 직접 받아서 빌드까지 한다고 하니, 이를 확인하려면, 개인 보다는, 상시로 켜져있는 클라우드에 윈도우 서버를 설치. (클라우드는 AWS 무료서버 추천)
3. Super socket
소켓 프로그래밍이 제공되나, 필수적인 기능들이 대부분 미구현, 로우레벨 라이브러리
## 보편적인 자바로 서버 구축
현재 C#으로 작성된 파일을 전부다 JAVA로 변경해야됨.
node.js 등으로 구동하도록 할 수는 있지만, Unity와의 호환성 문제로 여러가 문제가 발생 가능
***
제 생각으로는, Photon server로 구현을 하거나 aws에 윈도우 서버를 구축하는게 가장 빠르고 쉬울거라고 생각합니다. 
이에 대한 의견 부탁드립니다.

**Comment by gdevhun** [comment]
유니티가 포톤과 친숙하긴합니다. 다른것도 상관없을 듯합니다.

**Comment by CoEf** [comment]
교수님이 어느정도 수준으로 서버를 만들라고 하셨나요?
제가 만든 로그인 코드는 크게 api통신과 에러처리로만 나눠지기에 프론트엔디 선에서 나와있어도 보안상 크게 문제가 안될겁니다
그래서 굳이 서버로 옮길 필요가 없고 로그인 기능에서 서버로 옮길만한 기능은 유저 정보에 관한 토큰 정보나 api키 정보 입니다
그래서 로그인 코드 기준으로만 보면 서버를 크게 만들필요 없고 다른 언어를 쓸 기회가 있는 node js 가 더 편하고 좋긴 합니다. 어차피 저희 코드가 실시간 멀티플레이가 필요한 게 아니라 더 그렇기도 하고요.
그런데 이제 다른 분들이 만든 코드를 옮기는게 너무 힘이 든다 싶으면 다른 방식을 고르는게 나을 수 있겠죠

**Comment by Hyodonjoo** [comment]
> 교수님이 어느정도 수준으로 서버를 만들라고 하셨나요? 제가 만든 로그인 코드는 크게 api통신과 에러처리로만 나눠지기에 프론트엔디 선에서 나와있어도 보안상 크게 문제가 안될겁니다 그래서 굳이 서버로 옮길 필요가 없고 로그인 기능에서 서버로 옮길만한 기능은 유저 정보에 관한 토큰 정보나 api키 정보 입니다 그래서 로그인 코드 기준으로만 보면 서버를 크게 만들필요 없고 다른 언어를 쓸 기회가 있는 node js 가 더 편하고 좋긴 합니다. 어차피 저희 코드가 실시간 멀티플레이가 필요한 게 아니라 더 그렇기도 하고요. 그런데 이제 다른 분들이 만든 코드를 옮기는게 너무 힘이 든다 싶으면 다른 방식을 고르는게 나을 수 있겠죠

서버를 구축해서 해당 서버와 통신을 하는 것(토큰을 어떻게 보내고, 통신에 지장이 없는지)가 프로젝트 점수 매기는 것이 핵심이라 그렇습니다. 그 통신 기반으로 swagger도 작성해서 제출해야하구요. 남은 기간이 얼마 남지 않았기 때문에, 이미 C#으로 제작한 코드를 node.js에서 구동하시키기엔 시간이 부족할것 같습니다. 

만약 어떤걸로 해도 상관이 없으시다면, Photon server로 구현하도록 하는게 어떨까요.
지금 당장 타과목 기말고사가 얼마 남지 않았기 때문에, 여러분과 함께 서버를 구축하는게 절실합니다.
