### ISSUE TITLE
GoogleLoginController.cs 에러

### ISSUE THREAD

**Issue by Hyodonjoo** [gdevhun/OSSTeamProject#38]
다음과 같은 오류가 발생하는데, 어떻게 해결해야할지 모르겠습니다.
혹시 해결법 아시는 분 계시면, 알려주세요.
![오류](https://github.com/gdevhun/SpaceCat/assets/102202498/72a40c2d-8827-4979-9f64-c4de1c338496)
![오류2](https://github.com/gdevhun/SpaceCat/assets/102202498/b7a9f40b-0b0a-4986-997a-659dfe3933ad)
***
정황상 Unity 패키지중 일부가 설치가 안된 것 같은데, 어떤 걸 설치해야 할지 모르겠습니다.

**Comment by gdevhun** [comment]
![image](https://github.com/gdevhun/SpaceCat/assets/150761282/d8fa87ed-a112-41c8-b426-37e415afd0d4)
packagemanager authentic 설치하면 됩니다!

현 상태는 설치하지 않아도, develop pull 하면 에러는 없을겁니다!
